name: CI
on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Build
      shell: bash
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --target defer_test --config Release --verbose
    - name: Run test
      shell: bash
      run: |
        test "${{ matrix.os }}" == "windows-latest" && cd build/test/Release
        test "${{ matrix.os }}" != "windows-latest" && cd build/test
        ./defer_test > actual.txt
        echo -n 0123 > expected.txt
        diff -u expected.txt actual.txt
